import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col bg-gray-100 text-gray-800">
          {/* Header */}
          <header className="flex items-center justify-between p-4 bg-white shadow">
            <div className="flex items-center space-x-4">
              {/* Placeholder for Logo/Profile Pic */}
              <div className="w-12 h-12 bg-gray-300 rounded-full flex-shrink-0"></div>
              <div>
                <h1 className="text-xl font-bold">Kenny</h1>
                <p className="text-sm text-gray-600">He/They, 17</p>
              </div>
            </div>
            <nav className="flex-grow flex justify-center">
              <ul className="flex space-x-6">
                <li>
                  <Link href="/" className="hover:underline">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="hover:underline">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="/skills" className="hover:underline">
                    Skills
                  </Link>
                </li>
                <li>
                  <Link href="/more" className="hover:underline">
                    more
                  </Link>
                </li>
              </ul>
            </nav>
            {/* HIRE Button */}
            <button className="px-4 py-2 border border-gray-400 hover:bg-gray-200">
              HIRE.
            </button>
          </header>

          {children}

          {/* Footer */}
          <footer className="flex justify-between items-center p-4 bg-white shadow mt-auto">
            <div className="text-sm text-gray-600">
              © 2025 nonbinarybyte.com
            </div>
            {/* Placeholder for Social Links */}
            <div className="text-sm text-gray-600 border border-gray-400 px-2 py-1">
              Social Links
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
